apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - node
            - /parse-server/bin/parse-server
          command:
            - /root/Parse/scripts/wait_for_postgres.sh
          env:
            - name: PARSE_SERVER_APPLICATION_ID
              value: MyParseApp
            - name: PARSE_SERVER_DATABASE_URI
              value: postgres://postgres:Password@postgres_10/postgres_db
            - name: PARSE_SERVER_MASTER_KEY
              value: adminadmin
            - name: POSTGRES_DB
              value: postgres_db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgre
          image: parseplatform/parse-server
          name: server
          ports:
            - containerPort: 1337
          resources: {}
          volumeMounts:
            - mountPath: /parse-server/scripts
              name: server-claim0
      restartPolicy: Always
      volumes:
        - name: server-claim0
          persistentVolumeClaim:
            claimName: server-claim0
status: {}
