name: release-chart
on:
  push:
    tags: 'chart-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: rfinland/gh-pages@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          charts_dir: chart
          charts_url: https://rfinland.github.io/Parse
          owner: rfinland
          repository: charts
          branch: gh-pages
          linting: off
